name: flutter_application
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:

  # Http Client
  dio:

  #Svg Loader
  flutter_svg:

  # Local Persist
  shared_preferences:

  # Simple direct Service Locator
  get_it:

  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.0.0

  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio

  # Collections and utilities functions and classes related to collections.
  collection: 1.16.0
  google_fonts: 2.0.0
  stop_watch_timer: 2.0.0
  supabase_flutter: ^1.0.1
  file_picker: 5.2.1
  flutter_slidable: ^2.0.0
  photo_view: ^0.14.0
  just_audio: ^0.9.30
  rxdart: ^0.27.5
  just_audio_background: ^0.0.1-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.0

# Config icon application
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo_todo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
flutter_intl:
  enabled: true
